services:
  meilisearch:
    image: getmeili/meilisearch:v1.6
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_ENV=development
    volumes:
      - meilisearch_data:/meili_data
    networks:
      - meilisearch-network

  meilisearch-mcp:
    build: .
    environment:
      - MEILI_HTTP_ADDR=http://meilisearch:7700
      - MEILI_MASTER_KEY=masterKey
    depends_on:
      - meilisearch
    networks:
      - meilisearch-network
    stdin_open: true
    tty: true

volumes:
  meilisearch_data:

networks:
  meilisearch-network:
    driver: bridge