# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Base image with Python 3.12
FROM python:3.12-slim-bookworm

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set work directory
WORKDIR /app

# Install universal virtualenv (uv)
RUN pip install uv

# Copy the whole project into the Docker image
COPY . /app

# Install dependencies
RUN uv venv && \
    .venv/bin/uv pip install -e .

# Expose the necessary port (assuming default port)
EXPOSE 7700

# Entry point to run the server module
ENTRYPOINT [".venv/bin/python", "-m", "src.meilisearch_mcp"]
